### ISSUE TITLE
chef git activescaffold failed

### ISSUE THREAD

**Issue by sburns90** [opencrowbar/core#492]
I am trying to get starting using OpenCrowbar however when I attempt to run:
*production.sh my.FQDN.here*
I get an error when the script attempts to git activescaffold.
The important text from the exact error is:

*Git error: command `git rev-parse 190145f4905a88` in directory
...
STDERR: fatal: ambiguous argument '190145f4905a88': unknown revision or path not in the working tree.*

Here is the entire text from the error that occurred. http://pastebin.com/CJS3zKka

I am running CentOS 6.5 (64bit) basic server install.
Previously I had tried updating Cent but I had problems more problems trying to install OCB even when I used the --develop flag.

**Comment by galthaus** [comment]
When did you try this? I pushed RPMs yesterday around noon CST that address this issue.

**Comment by sjensen** [comment]
You will need to re-download the RPMs. in order to get the fix.

**Comment by galthaus** [comment]
In the following file:
/opt/opencrowbar/core/rails/Gemfile

The activescaffold line should look like:
gem 'active_scaffold'

You should be able to remove Gemfile.lock from the rails directory and rerun production.sh.

All this should be fixed in the latest RPM should be opencrowbar-core-2.1.0.4306-1.noarch.rpm.

**Comment by sburns90** [comment]
Thanks for the quick replies. I am running the install with the new RPMs and haven't had any problems.

Yesterday I tried running production.sh but it was from RPMs I that were 2 days old.
